apiVersion: v1
kind: Secret
metadata:
  name: {{ template "top-speed.fullname" . }}-params-secret
  labels:
    {{ include "top-speed.labels" . | nindent 4 }}
type: Opaque
stringData:
  params.properties: |
    eviction-sec=10
    trigger-meters=50

