test_suite(
    name = "unit-tests",
    tests = [
    ],
)

test_suite(
    name = "int-tests",
    tests = [
    ],
)

alias(
    name = "top_speed",
    actual = "//top_speed/src/main/java/com/fintechstudios/ff_sf2020/top_speed",
)

test_suite(
    name = "lint",
    tests = [
        "//top_speed/src/main/java/com/fintechstudios/ff_sf2020/top_speed:lint",
    ],
)
