##  Set to 'prod' to mark this job as a ververica-supported deployment
#
env: dev

## VVP-specific deployment target and namespace
# Created in the `infrastructure` chart
#
vpDeploymentTarget: "top-speed"
vpNamespace: "top-speed"

###  Annotations and labels for the VpDeployment itself,
##  not the created pods
#
# annotations:
# labels:

## Job Configuration

maxSavepointCreationAttempts: 4
maxJobCreationAttempts: 4

resources:
  jobmanager:
    cpu: "1"
    memory: 1g
  taskmanager:
    memory: 1g

parallelism: 1

flinkConfiguration:
  state.backend: "rocksdb"
  state.checkpoints.num-retained: "2"
  state.checkpoints.dir: "s3://fts-ff-virtual-2020-state/top_speed/checkpoints/"
  state.savepoints.dir: "s3://fts-ff-virtual-2020-state/top_speed/savepoints/"
  high-availability: "vvp-kubernetes"
  flink.security.ssl.enabled: "true"
  high-availability.storageDir: "s3://fts-ff-virtual-2020-state/top_speed/high-availability/"

log4jLoggers:
  "": INFO  #  Root logger
  com.fintechstudios: DEBUG

# Default artifact configuration, though
# can be updated at deploy-time
#
artifactJarUri: "s3://fts-ff-virtual-2020-artifacts/top_speed/latest.jar"
artifactFlinkVersion: "1.9"
artifactFlinkImageRegistry: "registry.ververica.com"
artifactFlinkImageRepository: "v2.1/flink"
artifactFlinkImageTag: "1.9.2-stream2-scala_2.11"
artifactEntryClass: "com.fintechstudios.ff_virtual_2020.top_speed.TopSpeed"

# Pod configuration
#
podLabels: {}
podAnnotations:
  # AWS annotations supported by kube2iam/KIAM with access to get the Jar Artifact from S3
  iam.amazonaws.com/role: "k8s-dev-us-east-1-ff-virtual-2020-top-speed-role"

