package(default_visibility = ["//visibility:public"])


filegroup(
    name = "checkstyle-config",
    srcs = ["checkstyle.xml"],
)

filegroup(
    name = "checkstyle-suppressions",
    srcs = ["checkstyle-suppressions.xml"],
)
